module.exports = [
  ['VB PRP DT NN IN IN DT JJ JJ TO VB JJ NN IN DT JJ NN IN NN !', 'Let us all turn out in the general offensive to hasten final victory in the revolutionary spirit of Paektu!'],
  ['VB PRP VB DT CD DT NNS IN JJ NN CC NNP VBG IN JJ JJ NN CC JJ NN NNS !', 'Let us greet the 70th anniversaries of national liberation and Party founding with high political enthusiasm and brilliant labour feats!'],
  ['VB PRP VB DT CD DT NNS IN JJ NN CC NNP VBG IN JJ , JJ NNS JJ IN DT NN IN NNP FW NNP PRP NN CC NNP NNP FW PRP NNP !', 'Let us glorify the 70th anniversaries of national liberation and Party founding as revolutionary, auspicious events noteworthy in the history of Kim Il Sung\'s nation and Kim Jong Il\'s Korea!'],
  ['DT JJ NNPS NNP FW NNP CC NNP NNP FW VBP DT JJ NNS IN PRP$ NN , DT NN IN NN CC DT NN IN DT VBN JJ NN NN .', 'The great Comrades Kim Il Sung and Kim Jong Il are the eternal leaders of our revolution, the sun of Juche and the incarnation of the dignified powerful Paektusan nation.'],
  ['VB PRP VB DT JJ NNPS NNP FW NNP CC NNP NNP FW IN DT JJ NNS IN PRP$ NNP CC NNS CC IN DT NN IN NN !', 'Let us uphold the great Comrades Kim Il Sung and Kim Jong Il as the eternal leaders of our Party and people and as the sun of Juche!'],
  ['DT JJ NNPS NNP FW NNP CC NNP NNP FW MD RB VB IN PRP !', 'The great Comrades Kim Il Sung and Kim Jong Il will always be with us!'],
  ['VB PRP VB DT NN NNP IN DT NNP RB IN DT NN NN IN NN , IN DT JJ NN TO DT NN IN DT NNS !', 'Let us glorify the Kumsusan Palace of the Sun eternally as the supreme sanctuary of Juche, as a grand monument to the immortality of the leaders!'],
  ['VB PRP NN PRP RB IN DT JJ NNS IN DT JJ NNPS NNP FW NNP CC NNP NNP FW !', 'Let us arm ourselves firmly with the revolutionary ideas of the great Comrades Kim Il Sung and Kim Jong Il!'],
  ['NNP VB DT JJ NN !', 'Long live the great Kimilsungism-Kimjongilism!'],
  ['VB PRP NN DT JJ NNP CC DT NN IN NN !', 'Let us model the whole Party and all society on Kimilsungism-Kimjongilism!'],
  ['VB PRP NN RB VBN RB IN NN NN CC NN MD IN NN DT NNS IN NN NNP FW NNP CC DT NNS CC NNS IN NN NNP NNP FW !', 'Let us advance vigorously united firmly with one mind and one will as befit the descendants of Comrade Kim Il Sung and the soldiers and followers of Comrade Kim Jong Il!'],
  ['VB PRP VB DT NNS IN NN IN NN NNP NNP FW IN PRP$ NN !', 'Let us cherish the ties of kinship with Comrade Kim Jong Il as our lifeline!'],
  ['VB PRP VB DT JJ JJ NNS CC JJ NNS IN DT JJ NNPS NNP FW NNP CC NNP NNP FW IN DT NNS TO VB !', 'Let us glorify the noble revolutionary careers and undying exploits of the great Comrades Kim Il Sung and Kim Jong Il for all generations to come!'],
  ['VB PRP VB DT NN IN JJ NN IN NNP NNP FW NNP , NN IN JJ NN CC JJ NN IN DT JJ NN , IN DT NN !', 'Let us glorify the achievement of national liberation by Generalissimo Kim Il Sung, hero of national resurrection and legendary hero of the anti-Japanese war, for all eternity!'],
  ['NNP VB DT JJ NN IN DT NN IN NNP !', 'Long live the great victory in the war against Japan!'],
  ['VB PRP VB DT JJ NNP NNP NNP FW PRP NNS IN CC NNS IN DT NN NN RB IN DT NNS !', 'Let us glorify the great Generalissimo Kim Jong Il\'s ideas of and achievements in the Songun revolution down through the generations!'],
  ['VB PRP RB VB CC VB DT JJ JJ NNS IN PRP$ NNP !', 'Let us brilliantly inherit and develop the glorious revolutionary traditions of our Party!'],
  ['VB PRP VB DT JJ NN IN DT JJ NN IN NN , DT NN IN DT NNS IN NN !', 'Let us accomplish the Korean revolution in the revolutionary spirit of Paektu, the spirit of the blizzards of Paektu!'],
  ['DT NNS CC NNS VBD IN DT JJ NNPS NNP FW NNP CC NNP NNP FW CC PRP$ NNS VBP NNS IN DT NN .', 'The lines and policies advanced by the great Comrades Kim Il Sung and Kim Jong Il and their instructions are textbooks for the revolution.'],
  ['VB PRP VB IN DT NN NNS IN DT JJ NNPS NNP FW NNP CC NNP NNP FW WDT DT NNS IN DT NN IN NN CC IN DT NN IN NN !', 'Let us carry out the lifetime instructions of the great Comrades Kim Il Sung and Kim Jong Il whatever the conditions without an inch of deflection and without a step of compromise!'],
  ['VB PRP NN JJ IN DT NN IN NN , NN CC NN VBD IN DT JJ NNPS NNP FW NNP CC NNP NNP FW !', 'Let us advance straight along the road of independence, Songun and socialism opened by the great Comrades Kim Il Sung and Kim Jong Il!'],
  ['VB PRP VB PRP$ NN IN DT RBS JJ NN IN DT NN , IN DT NNS PRP NN , IN VBD IN DT JJ NNPS NNP FW NNP CC NNP NNP FW !', 'Let us build our country into the most powerful one in the world, into a people\'s fairyland, as wished by the great Comrades Kim Il Sung and Kim Jong Il!'],
  ['VBP VBG DT NN DT JJ NNPS NNP FW NNP CC NNP NNP FW VBD !', 'Do everything the way the great Comrades Kim Il Sung and Kim Jong Il did!'],
  ['VB PRP NN IN DT VBG IN DT JJ NN IN VBG NNP NNP FW PRP NN !', 'Let us step up the building of a prosperous country by applying Kim Jong Il\'s patriotism!'],
  ['VB PRP VBP DT NN IN DT JJ NNP FW NNP PRP NN , NNP NNP NNP FW PRP NN , VBG DT NN IN NN NNP NNP FW !', 'Let us exalt the brilliance of the great Kim Il Sung\'s country, General Kim Jong Il\'s country, following the leadership of Comrade Kim Jong Un!'],
  ['VB PRP RB VB , VBG DT VBN NN NNP NNP FW , DT NN IN VBD IN NN !', 'Let us stoutly continue, following the respected Comrade Kim Jong Un, the march that started on Paektu!'],
  ['DT VBN NN VBZ DT JJS NN CC DT RBS JJ NN IN PRP$ NN .', 'The single-hearted unity is the greatest foundation and the most powerful weapon of our revolution.'],
  ['VB PRP VB IN PRP$ RB NNS DT NNP NNP NNP VBN IN DT JJ NN NNP NNP FW !', 'Let us defend with our very lives the Party Central Committee headed by the great Comrade Kim Jong Un!'],
  ['VB PRP VB DT VBN NN IN DT NNP CC JJ NNS IN DT VBN NN NNP NNP FW IN DT JJ NN CC VB PRP NN !', 'Let us defend the single-hearted unity of the Party and revolutionary ranks around the respected Comrade Kim Jong Un in a thoroughgoing way and consolidate it rock-solid!'],
  ['VB DT DT NN NNS CC NNS NN NNS CC NNS IN NN IN DT VBN NN NNP NNP FW !', 'Let all the service personnel and people form rings and rings of fortress around the respected Comrade Kim Jong Un!'],
  ['NNP VB DT JJ NNPS NNP IN NNP , WDT VBZ CC NNS DT NNS IN PRP$ NNS !', 'Long live the glorious Workers\' Party of Korea, which organizes and guides all victories of our people!'],
  ['VB PRP VB CC VB DT NNPS NNP IN NNP IN DT NNS TO VB IN DT JJ NN IN NNPS NNP FW NNP CC NNP NNP FW !', 'Let us strengthen and develop the Workers\' Party of Korea for all ages to come into a glorious party of Comrades Kim Il Sung and Kim Jong Il!'],
  ['VB PRP VBN IN DT JJ NN IN VBG DT NNP PRP NN NN CC VBG NN IN DT NN , WDT NNS PRP$ CD DT VBG NN !', 'Let us set up a new milestone in improving the Party\'s leadership ability and fighting efficiency in this year, which marks its 70th founding anniversary!'],
  ['VB PRP VB DT NNP PRP JJ NN NN JJR RB IN DT NNP CC NN !', 'Let us establish the Party\'s monolithic leadership system more thoroughly across the Party and society!'],
  ['VB DT JJ NNP NN DT NNS , VB DT JJ NN CC VB NN IN DT NNP NNP NNP !', 'Let the whole Party share the ideas, breathe the same air and keep pace with the Party Central Committee!'],
  ['VB PRP VB IN DT NNP JJ NN IN WDT PRP NNS IN NN IN DT JJ NN IN DT NNP NNP NNP !', 'Let us establish across the Party rigorous discipline by which it moves as one under the unified leadership of the Party Central Committee!'],
  ['VB PRP VB DT NN IN DT NNP NNP NNP IN DT NN JJ IN DT NN TO VB DT NNP PRP NNS CC NN PRP$ NNS !', 'Let us defend the prestige of the Party Central Committee in every way possible through the struggle to implement the Party\'s ideas and champion its policies!'],
  ['VB PRP$ NNS CC NNS IN NNS IN NN DT NN IN DT NN IN DT NNP NNP NNP , NNS WRB DT NNP PRP VB , NN CC NN VB JJ !', 'Turn your units and areas into places that adjoin the yard of the office of the Party Central Committee, places where the Party\'s call, breath and pulse run high!'],
  ['VB IN IN DT NN IN DT NNP PRP NNS CC NNS IN DT JJ NN IN NNP NN !', 'Keep up with the implementation of the Party\'s lines and policies as the major line of Party work!'],
  ['PRP VB DT NNS !', 'We serve the people!'],
  ['VB PRP VB DT NN IN VBG DT NNS JJS VB IN NNP NN IN DT JJ !', 'Let us make the principle of holding the masses dearest run through Party work as a whole!'],
  ['VB PRP VB DT NN IN VBG , JJ CC VBG IN DT NNS VB IN DT NNP !', 'Let us make the climate of respecting, loving and relying on the people prevail across the Party!'],
  ['NNP DT JJ NN IN NNP NN IN VBG DT NNS PRP JJ IN VBG !', 'Focus the major effort in Party work on improving the people\'s standard of living!'],
  ['VB NNP NNS CC NNS NN RB IN DT NNS TO VB IN TO PRP$ JJS NNS !', 'Let Party organizations and officials work devotedly for the people to live up to their highest expectations!'],
  ['VB DT JJ NNP JJ PRP$ JJ NN TO DT NN IN DT NNS !', 'Let the whole Party direct its main effort to the work with the people!'],
  ['VB DT NNS IN NNS JJ IN NN CC NN IN DT NN CC DT VBG IN NN IN VBZ DT RB NN !', 'Raise all people into ones strong in idea and faith with the affection and the feeling of kinship as befits a motherly party!'],
  ['RB IN NN MD VBP CD IN NN IN NNS CC RB NN IN NN IN NN CC NN , RB NN PRP CC VB PRP TO VB IN DT JJ NN !', 'Even though one may have 99 per cent of demerits and only one per cent of merit or conscience, boldly trust him and lead him to start with a clean slate!'],
  ['NN VBG VB TO DT JJ NN IN DT NNS IN DT JJ VBG , JJ NN , IN NNP NN !', 'Regard giving play to the spiritual strength of the masses as the main thing, compulsory path, of Party work!'],
  ['VB NNP NNS VB DT NNP PRP NNS IN NN IN DT NNS CC VB JJ IN VBG PRP CC VBG VB TO PRP$ JJ NN !', 'Let Party officials learn the Party\'s methods of work with the people and become skilful in remoulding them and giving play to their spiritual strength!'],
  ['RB VB JJ IN NN IN NN CC NN !', 'Thoroughly get rid of abuse of authority and bureaucratism!'],
  ['NN RB NN NN IN DT JJ NN IN DT JJ NN IN NNP NN !', 'Regard supply service work as an important link in the whole chain of Party work!'],
  ['VB NNP NNS VB VBG NNS CC NNS IN VBG DT NNP PRP NNS !', 'Let Party cells become death-defying corps and pioneers in implementing the Party\'s policies!'],
  ['VB PRP VB JJ NN IN DT JJ JJ JJ !', 'Let us hasten final victory through a revolutionary ideological offensive!'],
  ['VB RB TO JJ NN IN DT JJ NN !', 'Hold fast to ideological work as the top priority!'],
  ['VB PRP VB DT JJ NN IN VBG DT JJ NN !', 'Let us raise a strong wind of studying the great Kimilsungism-Kimjongilism!'],
  ['VB IN NN IN DT NN IN DT NNS , NNP NNP FW PRP NN , NN , NN CC NN NN , CC NN !', 'Concentrate on education in the greatness of the leaders, Kim Jong Il\'s patriotism, faith, anti-imperialist and class consciousness, and morality!'],
  ['VB DT JJ NN TO DT NN !', 'Keep the revolutionary faith to the death!'],
  ['VB RB IN PRP$ NN CC NN !', 'Fight death-defyingly for our country and nation!'],
  ['VB PRP VB JJ IN NN DT NNS IN DT NN NN CC PRP$ NN !', 'Let us bear deep in mind the lessons from the class struggle and its truth!'],
  ['VB DT NNP PRP NN NNS NN IN DT NNS IN DT JJ NN NN VBD !', 'Let the Party\'s information officials work as the buglers of the anti-Japanese guerrilla army did!'],
  ['VB DT JJ IN DT NNP PRP NNS IN PRP VBP IN PRP$ JJ RB NNS !', 'Make all well-informed of the Party\'s policies as they are of their own family affairs!'],
  ['NNP DT VBG NN IN DT JJ NN CC VB PRP$ NN VBN , JJ CC JJ !', 'Fire an opening salvo of an ideological campaign and make our fire concentrated, regular and accurate!'],
  ['NN IN DT NN JJ NN NN !', 'Step up the three-revolution red flag movement!'],
  ['VBP DT NN NNS IN JJ CC JJ NN IN NN IN PRP$ JJ NN CC NN !', 'Frustrate the imperialist moves for ideological and cultural infiltration by dint of our revolutionary ideology and culture!'],
  ['VB DT JJ NNP VB NN CC NN NNS !', 'Let the whole Party become information and motivation workers!'],
  ['VB DT JJ NN IN NN NNS IN DT NNPS NNP IN NNP IN DT NN PRP JJ JJ JJ TO DT NN VBN IN NN IN PRP$ NN !', 'Demonstrate the revolutionary mettle as befit members of the Workers\' Party of Korea in the today\'s general offensive true to the pledge taken in front of its flag!'],
  ['PRP$ NNP PRP JJ NN IN RB VBG DT NN NNS VBZ DT JJ JJ NN IN PRP MD VB IN JJ IN EX VBZ DT NN IN NN IN DT NNS .', 'Our Party\'s new line of simultaneously promoting the two fronts is a permanent strategic line that we must pursue as long as there exists the threat of aggression by the imperialists.'],
  ['DT IN IN DT NN TO VB DT NNP PRP NN IN RB VBG DT NN NNS !', 'All out for a campaign to implement the Party\'s line of simultaneously promoting the two fronts!'],
  ['DT NNS PRP NNP VBZ DT NN CC JJ NN IN DT NN NN CC DT JJ VBN NN IN DT NNPS NNP IN NNP .', 'The People\'s Army is the pillar and main force of the Songun revolution and a revolutionary armed force of the Workers\' Party of Korea.'],
  ['VB PRP NN DT JJ NN IN NN !', 'Let us model the entire army on Kimilsungism-Kimjongilism!'],
  ['VB DT CD DT NNS IN JJ NN CC NNP VBG IN JJ NNS IN VBG DT NN PRP JJ NN !', 'Adorn the 70th anniversaries of national liberation and Party founding with proud successes in consolidating the country\'s military strength!'],
  ['VB DT NNS PRP NNP VB DT JJ NN CC JJ NN IN DT NN NN VBG RB DT JJ NN IN DT NNPS NNP IN NNP IN DT JJ NNS IN DT NN !', 'Let the People\'s Army remain the reliable vanguard and solid cornerstone of the Songun revolution holding aloft the red flag of the Workers\' Party of Korea as the foremost colours of the revolution!'],
  ['VB DT NNS CC NN NNS IN NN CC VB DT NN IN NNP . NN RB TO DT NN !', 'Become the props and iron shields that support and defend the lineage of Mt. Paektu alone to the death!'],
  ['VB DT VBN NNP NNP NNP NNP FW PRP JJ NN NN JJR RB IN DT NN !', 'Establish the respected Supreme Commander Kim Jong Un\'s monolithic command system more firmly throughout the army!'],
  ['VB TO DT NN DT JJ JJ NN CC NN JJ NNS IN VBG JJ NN !', 'Implement to the letter the four-point strategic line and three major tasks for increasing military strength!'],
  ['VB DT JJ NN DT VBG NN IN NNS WP NN JJ RB IN PRP$ NNS VBN RB IN DT NN VBD IN DT NNP !', 'Make the entire army the leading force of guards who advance straight ahead with their guns levelled only in the direction indicated by the Party!'],
  ['VB DT NNS PRP NNP VB DT NN JJ IN NN CC NN , DT NN IN VBG NN CC DT NN NN IN DT NN , WDT VBZ RB JJ TO DT NNP CC DT NN !', 'Let the People\'s Army become an army strong in idea and faith, a pioneer in achieving unity and the first guardian of the unity, which is unfailingly loyal to the Party and the leader!'],
  ['VB DT JJ NN VB DT NN IN JJ NN !', 'Let the entire army become a unit of genuine comrades-in-arms!'],
  ['VB IN DT NN DT JJ CC JJ MD IN NNP NNP FW PRP JJ JJ NN IN RB VBG DT NN IN VBG DT NNS IN IN NNP VBN CD DT NNP CC NNPS NN !', 'Consolidate in every way the political and military might of Kim Jong Un\'s powerful revolutionary army by vigorously conducting the movement of winning the titles of O Jung Hup-led 7th Regiment and Guards Unit!'],
  ['VB NN TO PRP$ JJ VBN NNS JJ NN IN VBG DT NNS !', 'Add brilliance to our revolutionary armed forces\' proud tradition of winning all battles!'],
  ['DT NN VBZ DT NN IN JJ NN , IN WDT PRP MD NN DT CD DT NN IN DT NN IN DT JJ NN IN JJ VBG IN DT JJ NNP NNP FW NNP CC DT CD DT NN IN DT NN IN DT NN JJ NNS IN JJ VBG IN DT JJ NNP NNP NNP FW .', 'This year is a year of great significance, in which we will mark the 40th anniversary of the publication of the five-point policy for military training by the great Generalissimo Kim Il Sung and the 25th anniversary of the formulation of the four major principles for military training by the great Generalissimo Kim Jong Il.'],
  ['VBG VBZ RB DT NN !', 'Training is also a battle!'],
  ['VB DT JJ NN NN IN NN IN VBG VBG IN JJ NNS VBD IN NNP . NN !', 'Let the entire army bubble with enthusiasm for intensifying training as anti-Japanese guerrillas did on Mt. Paektu!'],
  ['VB DT JJ NN IN DT NN IN VBG DT NN IN NN CC JJ VBG !', 'Glorify this significant year as a milestone in improving the quality of combat and political training!'],
  ['VB DT JJ NN VB VBN IN NN NNS IN VBG JJR RB DT NNS IN DT NN IN VBG JJ NNS CC NNS !', 'Let the entire army be prepared as crack shots by raising more fiercely the flames of the movement of becoming accurate riflemen and gunners!'],
  ['MD DT NN VB TO VB PRP$ NN , VB PRP TO DT JJ NN RB IN NN IN PRP MD VB TO NN DT NN IN NN !', 'Should the enemy dare to invade our country, annihilate them to the last man so that none of them will survive to sign the instrument of surrender!'],
  ['VB RB IN DT JJ IN DT NN PRP NN !', 'Be constantly on the alert without a moment\'s relaxation!'],
  ['VB NN NN TO VB DT NNS PRP NNP IN DT NN JJ NN TO DT NN !', 'Establish iron discipline to develop the People\'s Army into an elite revolutionary force to the hilt!'],
  ['DT NNS , VB NN NNS WP VBP JJ IN VBG IN JJ NN !', 'All officers, become field commanders who are capable of dealing with modern warfare!'],
  ['VB PRP VB NNS CC NNS IN NNS , NN NN NNS CC VB PRP NNS JJ NNS CC NNS IN NN DT NN IN DT NN IN DT NNP NNP NNP !', 'Let us develop battalions and companies into ever-victorious, elite combat units and make them soldiers\' dear villages and homes that adjoin the yard of the office of the Party Central Committee!'],
  ['VB DT NN IN NN NNS IN VBG VBN NNS TO VB NN NN VBG , VBG CC NN NN IN DT JJ NNS !', 'Enrich the life of service personnel by making sustained efforts to develop soy bean farming, fishing and animal husbandry as the main thrusts!'],
  ['DT RB NN NNS IN DT NNS PRP NNP , NN IN NN IN PRP$ NNS IN DT IN DT JJ NN NN !', 'The supply service officers of the People\'s Army, work with devotion for their soldiers like those of the anti-Japanese guerrilla army!'],
  ['VB JJ VB TO DT VBN NN CC VBG NN IN DT NNS PRP NNP IN DT JJ NNS IN VBG DT VBG NN !', 'Give full play to the match-for-a-hundred spirit and fighting efficiency of the People\'s Army on the major fronts of building a thriving nation!'],
  ['VB DT NN CC NNS !', 'Serve the country and people!'],
  ['NNP DT NNS !', 'Aid the people!'],
  ['VB DT NNS IN NNS VB JJ NNS TO PRP$ NNS !', 'Let the wives of officers become dependable assistants to their husbands!'],
  ['NNS CC NNS IN DT JJ NNS PRP NNP NNP NNPS , VB DT NN IN VBG PRP$ NN , NN CC NNS !', 'Officers and men of the Korean People\'s Internal Security Forces, sharpen the sword for defending their leader, system and people!'],
  ['VB PRP VB NN NNS CC JJ NNS WP VB PRP$ NNP , NN CC NNS TO DT NN !', 'Let us become iron shields and red warriors who defend our Party, system and people to the death!'],
  ['VB PRP VB DT NN IN VBG NN TO JJ NNS JJR RB IN NN !', 'Let us establish the climate of attaching importance to military affairs more firmly across society!'],
  ['DT NN VBN NNPS VBZ DT JJ VBN NN IN PRP$ NNP CC DT JJ VBG IN DT NNS PRP NNP .', 'The Worker-Peasant Red Guards is a revolutionary armed force of our Party and a reliable wing of the People\'s Army.'],
  ['DT NN VBN NNPS CC DT NNP VBN NNPS , VB RB VBN IN DT NN NN IN VBG VBG IN DT NN NN !', 'The Worker-Peasant Red Guards and the Young Red Guards, be fully prepared for an all-people resistance by intensifying training in a real-war atmosphere!'],
  ['VB PRP VB DT JJ NN IN DT JJ NN IN DT JJ NN IN DT NN CC NNS !', 'Let us turn the whole country into a socialist fairyland by the joint operation of the army and people!'],
  ['VB PRP VB JJ NN IN DT NN IN DT JJ NN NN CC NN NN VBN IN DT JJ NN NN !', 'Let us achieve final victory on the strength of the great army-people unity and all-people resistance based on the revolutionary soldier spirit!'],
  ['RB VB DT NN PRP VBD IN DT NN !', 'Always live the way you did as a soldier!'],
  ['VB PRP VB IN DT NNS IN DT WP VBD IN NN , VBN JJ NNS , NN NNS CC NNS NNS IN NN !', 'Let us look after the families of those who fell in action, honoured disabled soldiers, war veterans and soldiers\' families with sincerity!'],
  ['NN NN VBZ DT JJ NN IN DT NN NN .', 'Defence industry is the reliable arsenal of the Songun revolution.'],
  ['NN DT JJ VB IN VBG NN NN IN VBG JJ VB TO DT NN IN NN !', 'Effect a fresh turn in developing defence industry by giving full play to the spirit of Kunja-ri!'],
  ['RB VB CC JJ JJ JJ JJ NN IN PRP$ JJ NN !', 'Proactively develop and perfect powerful cutting-edge military hardware of our own style!'],
  ['NN IN DT NNS TO VB NN NN VBN CC JJ , JJ CC JJ !', 'Step up the efforts to make defence industry Juche-oriented and independent, modern and scientific!'],
  ['VB DT NN NN NN VB DT JJ NN TO VBG DT JJ NN CC VBG DT NNS PRP JJ IN VBG !', 'Let the defence industry sector make a positive contribution to building an economic giant and improving the people\'s standard of living!'],
  ['PRP$ NNP VBZ JJ IN PRP$ NN TO VB PRP$ NNS , WP VBP DT JJS IN DT NN , VB DT JJ NNS IN RB IN JJ .', 'Our Party is steadfast in its determination to make our people, who are the best in the world, enjoy all socialist benefits as soon as possible.'],
  ['VB PRP VBP DT JJ NNS VBN IN DT JJ NN NNP NNP NN DT VBG IN DT JJ NN CC DT NN IN DT NNS PRP VBG NNS , IN NN TO VB PRP VB NN IN NN !', 'Let us tend the precious seeds sown by the great Comrade Kim Jong Ilfor the building of an economic giant and the improvement of the people\'s living standards, in order to make them bear fruit in reality!'],
  ['NNP CC NN VBZ DT NN IN JJ NN .', 'Science and technology is the engine of socialist construction.'],
  ['VB DT NN NN VB IN DT NN TO NN DT NN IN DT NN IN NN !', 'Let the science front stand at the forefront to fire a salvo for the triumph of socialism!'],
  ['VB PRP VB DT NN IN DT NNS IN NN IN NN !', 'Let us build a fairyland for the people by dint of science!'],
  ['NNP NN VBZ DT NN IN JJ NN IN NN !', 'Scientific research is an area of acute confrontation with imperialism!'],
  ['VB IN DT VBG NN !', 'Go beyond the cutting edge!'],
  ['VB DT JJ NN IN DT JJ NN IN VBG NN NN IN DT NN NNS CC VBG PRP$ JJ NN !', 'Accelerate the industrial revolution in the new century by introducing CNC technology into the production lines and achieving their full automation!'],
  ['NN JJR JJ NN NNS CC NNS NNS IN PRP$ NN !', 'Launch more cutting-edge sci-tech satellites and applications satellites of our style!'],
  ['VB DT NN IN NN CC NN IN NN NN CC NN !', 'Raise the level of modernization and scientification in weather survey and forecast!'],
  ['EX VBZ DT NN IN NN , CC PRP$ NNS CC NNS VBP DT JJ NN IN NN CC DT JJ NNP .', 'There is no border in science, but our scientists and technicians have the socialist motherland of Juche and the great Party.'],
  ['NNS CC NNS , VB IN DT NN IN DT NN TO VB DT VBG NN IN VBZ VBG , VBG CC VBG IN DT RB NN !', 'Scientists and technicians, stand in the vanguard of the struggle to build a thriving country that is developing, civilizing and advancing at a fast pace!'],
  ['VB DT NN CC NN IN DT NNP PRP NNS IN NN IN RB VBG JJ NN CC NN !', 'Prove the validity and vitality of the Party\'s policies in reality by proactively developing cutting-edge science and technology!'],
  ['VB NN NNS CC NN NNS IN JJ JJ CC JJ NNS !', 'Build "gold mountainsand "treasure mountainswith brilliant scientific and technological achievements!'],
  ['TO VB DT NN NN IN DT NNS CC VB PRP$ JJ NN IN DT JJR NN IN NN NN , NN NN CC VBG IN DT JJ NNS VBZ DT RBS JJ NN VBG PRP$ NNP IN JJ .', 'To resolve the food problem of the people and improve their dietary life on a higher level with crop cultivation, animal husbandry and fishing as the main thrusts is the most important task facing our Party at present.'],
  ['NNP VBZ DT NN IN DT NN NN IN DT RB NN IN DT NN TO VB NN CC DT JJ NN NN IN DT VBG IN DT JJ NN !', 'Agriculture is the trench on the first line of the forward echelon of the campaign to defend socialism and the main thrust area for the building of an economic giant!'],
  ['VB PRP VB IN NNS DT JJ NN IN NN NNS VBN IN DT JJ NN NNP NNP FW !', 'Let us glorify through generations the new history of "gold plainscreated by the great Comrade Kim Jong Il!'],
  ['VB PRP VB PRP$ NN NN IN NN IN VBG NNS NN !', 'Let us make our country overflow with rice by boosting cereals production!'],
  ['RB VB VBG VBG CC JJ JJ VBG NNS !', 'Actively introduce water-saving farming and other scientific farming methods!'],
  ['VB PRP NN JJ TO VB NN NNS IN DT NN NN !', 'Let us work hard to secure water resources as an all-people campaign!'],
  ['VB PRP VB JJ VBG IN DT JJ NN !', 'Let us encourage organic farming on an extensive scale!'],
  ['VB DT NN NN NN IN NN NN CC NN VBG , CC NN VBG CC NN VBG !', 'Establish the food production cycle of crop cultivation and livestock farming, and fruit growing and livestock farming!'],
  ['VB PRP VB DT NN IN NN VBG IN VBG PRP JJ , JJ CC JJ !', 'Let us beat the world in fruit farming by making it scientific, modern and intensive!'],
  ['VB NNS NN RB CC PRP$ JJ NN VB DT NN IN DT NN IN NN NNS IN DT NN IN NN NNP !', 'Make fruits cascade down and their sweet aroma fill the air on the sea of apple trees at the foot of Chol Pass!'],
  ['NNP NNS RB IN NNS !', 'Grow vegetables extensively in greenhouses!'],
  ['VB PRP VB PRP IN DT NN IN NNS IN VBG NN NN JJ , JJ CC VBN !', 'Let us turn ours into a country of mushrooms by making mushroom cultivation scientific, intensive and industrialized!'],
  ['DT NN PRP MD NN DT CD DT NN IN DT NN IN DT NN NN NN IN DT JJ NN NNP FW NNP , WDT VBZ DT JJ NN CC NN IN PRP$ NN TO VB CC VB IN NN .', 'This year we will mark the 50th anniversary of the creation of the sub-workteam management system by the great Comrade Kim Il Sung, which is the advantageous form and method of our style to organize and manage for production.'],
  ['VB DT NNS IN DT NN NN NN TO DT JJ !', 'Demonstrate the advantages of the sub-workteam management system to the full!'],
  ['RB RB DT NN NN NN IN DT NN NN NN IN NN TO VB PRP VB IN IN JJ NN !', 'Properly apply the field responsibility principle within the sub-workteam management system in order to make it pay off in agricultural production!'],
  ['NNP IN IN DT NNP NN NNP NN NN IN DT JJ NN IN VBG NN CC NN !', 'Press on with the South Hwanghae Province waterway project in the revolutionary spirit of death-defying implementation and self-reliance!'],
  ['VB PRP VB IN DT JJ NN NNS IN NN IN NN !', 'Let us carry through the great Generalissimos\' instructions on "grass for meat"!'],
  ['VB PRP VB DT NN IN DT JJ NN VBG NN IN DT NN NN !', 'Let us expedite the construction of the large-scale livestock farming base in the Sepho area!'],
  ['VB JJR NNS IN NN , NNS CC NN VBG JJ DT NN IN VBN NN VBG !', 'Produce larger quantities of meat, eggs and milk holding high the banner of science-based livestock farming!'],
  ['VB DT JJ NN IN NN NN IN VBG DT VBG NN IN DT NNS PRP NNP !', 'Create a new history of "gold seaby emulating the fishing sector of the People\'s Army!'],
  ['VB DT JJ NN NN IN NNP IN NNP NNP NN CC VB VBN IN DT JJ NN IN NN CC JJ NN !', 'Let this socialist country resound with Song of Big Fish Haul and be permeated with the fragrant smell of fish and other seafoods!'],
  ['VB VBG NNS CC NNS CC RB VB VBD VBG NNS !', 'Modernize fishing vessels and implements and actively introduce advanced fishing methods!'],
  ['VB DT JJ NN IN NN VBG NN IN DT NN !', 'Let the strong wind of fish farming blow across the country!'],
  ['NNP IN DT JJ NN NN CC JJ NN VBG IN NNS , NNS CC NNS !', 'Conduct on a large scale fish and other seafood farming in rivers, lakes and seas!'],
  ['RB VB DT NNS NNS IN DT NNS IN VBG DT JJ VBG IN NN NN !', 'Resolutely thwart the sanctions schemes of the imperialists by effecting a great upswing in light industry!'],
  ['VB JJR NNS IN JJ NN NNS WDT VBP VBN IN DT NNS CC VBP JJ NN IN DT NN NN !', 'Produce larger quantities of high-quality consumer goods which are favoured by the people and have competitive edge on the world market!'],
  ['VBN IN DT NN TO VB NN NNS RB VBN , NN CC NN !', 'Speed up the work to make foodstuff factories fully automated, germ- and dust-free!'],
  ['VB DT NN IN DT NNS VBG IN VBG DT NN IN PRP$ NNS !', 'Keep the laughter of the children ring by increasing the production of their foodstuffs!'],
  ['RBR JJ NN NNS CC NN NN NNS IN PRP$ JJ NNS !', 'More stylish school uniforms and quality school things for our dear children!'],
  ['VB JJS VB TO DT NN IN DT NN IN VBG NNP CD NN NNS !', 'Give fullest play to the vitality of the movement of producing August 3 consumer goods!'],
  ['VB DT NN NN VB DT JJ NN TO VBG DT NNS PRP JJ IN VBG IN VBG IN NN !', 'Let the Tanchon area make an active contribution to improving the people\'s standard of living by boosting up production!'],
  ['VB PRP VB DT NNS IN DT NNS PRP NN IN VBG DT NN IN DT JJ NN NNP NNP !', 'Let us turn all counties into the people\'s fairyland by applying the spirit of the historic Changsong Joint Conference!'],
  ['NNP VBZ DT NN IN DT JJ NN .', 'Electricity is the lifeline of the national economy.'],
  ['VB DT JJ NNP , DT JJ NN CC DT DT NNS VB VBD TO NN DT JJ NN RB !', 'Let the whole Party, the entire army and all the people be enlisted to increase the electric-power generation radically!'],
  ['JJ IN NN DT NN IN DT NN NN NNS IN DT NN NNP IN DT CD DT NN IN NNP VBG !', 'Complete with credit the construction of the multi-tier power stations on the Chongchon River until the 70th anniversary of Party founding!'],
  ['VBN IN DT NN IN DT NN NN NNP NNP NNP , NN NNP NNP , NN NNP NNP CC NN NN NNP NNP !', 'Speed up the construction of the Paektusan Songun Youth Power Station, Orangchon Power Station, Ryesonggang Power Station and Wonsan Army-People Power Station!'],
  ['VB DT NN IN DT VBG NN TO DT JJ CC VB DT NN IN NN IN NN !', 'Raise the efficiency of the generating equipment to the maximum and prevent the loss of power in transmission!'],
  ['VB PRP RB VB DT NN NN NN IN DT NN IN DT VBG NN !', 'Let us definitely convert the electricity control system of the country into an electricity-saving one!'],
  ['VB CC VB JJ NN IN NN , JJ , JJ CC JJ NN !', 'Develop and make effective use of wind, tidal, geothermal and solar energy!'],
  ['NNS !', 'Coal-miners!'],
  ['DT NN IN NN NNS VBZ DT NN IN NN NN CC DT NN IN DT VBG IN DT JJ NN .', 'The height of coal heaps means the increase in electricity generation and the tempo of the building of an economic giant.'],
  ['VB PRP NN DT NNP IN VBN NN NN !', 'Let us support the Party with increased coal production!'],
  ['VB NNS IN DT NN IN NN IN NN NN CC RB JJ NN IN JJR NNS TO DT JJ NN NNS !', 'Concentrate efforts on the production of coal for electricity generation and supply high-quality coal in larger amounts to the thermal power stations!'],
  ['VB JJ NN TO DT RB IN NN CC NNS VBN IN NN NN !', 'Give top priority to the supply of equipment and materials required for coal production!'],
  ['DT NN CC NN NNS VBP JJ NNS IN DT JJ NN .', 'The metal and chemical industries are twin buttresses of an economic giant.'],
  ['VB JJ NNS IN NN NN IN NN CC NN NN NNS !', 'Kindle fierce flames of production upsurge in Songjin and Chollima steel complexes!'],
  ['VB DT NN NN NN NN TO NN CC VB PRP$ NN IN DT JJ NN !', 'Bring the Juche iron production system to perfection and normalize its production on a high level!'],
  ['VB JJR NNS IN JJ NN NN TO JJ NNS !', 'Send larger quantities of high-grade iron ore to metallurgical factories!'],
  ['NN VBZ NN CC NN .', 'Fertilizer means rice and socialism.'],
  ['VB NN CC NN VB NN NN IN DT JJR NN !', 'Let Hungnam and Namhung produce Juche fertilizer in a larger amount!'],
  ['VB DT JJ NN NNS VB DT JJ NN TO VBG JJ NN IN JJ NNS IN NN NN CC VBG NNS !', 'Let the large-scale chemical factories make an active contribution to ensuring domestic production of raw materials for light industry and building materials!'],
  ['NNS VBP DT NNS IN DT NN .', 'Railways are the arteries of the country.'],
  ['VB DT NN NN NN VB JJ NN IN DT NN VBZ CC RB VB DT NNS IN DT JJ NN IN NN !', 'Let the rail transport sector establish rigid discipline as the army does and fully satisfy the demands by the national economy for transport!'],
  ['VB DT NN TO VB DT NNS JJ , JJ CC VBN !', 'Accelerate the work to make the railways heavy-duty, high-speed and IT-based!'],
  ['VB TO NN DT NN IN DT JJ NNS IN RB IN JJ !', 'Bring to completion the rehabilitation of the northern railways as early as possible!'],
  ['VB PRP VB DT NN IN DT NN NNS CC DT NNS JJ TO NNS IN DT JJ NNS IN DT NN NNS CC NNS !', 'Let us improve the appearance of the railway stations and the areas adjacent to railways by the concerted efforts of the service personnel and people!'],
  ['VB NN NN IN DT JJ JJ !', 'Develop air transport onto a new high!'],
  ['VB DT NN NNP IN DT JJ NN !', 'Build the Wonsan Port into a world-class one!'],
  ['VB CC VB DT NNS CC NN VBN IN NN !', 'Develop and manufacture the machines and equipment required for modernization!'],
  ['VB CC RB JJ VBD NN IN NN CC IN DT JJ NN !', 'Produce and supply major ordered equipment in time and in a qualitative way!'],
  ['VB CC VB JJ NN IN JJ JJ NNS IN DT NN !', 'Explore and make rational use of valuable underground resources of the country!'],
  ['VB JJ NN JJ CC JJ !', 'Make foreign trade multilateral and diversified!'],
  ['VB DT NN NNS IN DT NN . NN JJ NN NN CC JJ NN NNS !', 'Accelerate the development projects of the Wonsan-Mt. Kumgang international tourist zone and economic development parks!'],
  ['NNPS !', 'Builders!'],
  ['VB PRP NN IN DT JJ JJ NN IN NN IN RB VBG DT NNP PRP VBN NN IN NN !', 'Let us usher in a great golden age of construction by thoroughly applying the Party\'s Juche-oriented idea on architecture!'],
  ['VB IN IN JJR NNS JJ NNS IN WDT DT NN NN , JJ NN , NN , NN CC JJ CC JJ NN NN JJ NN !', 'Set up in larger numbers monumental structures in which the Juche character, national identity, originality, convenience and formative and artistic beauty form perfect harmony!'],
  ['VB RB TO DT NN IN VBG NN , JJ NN CC DT NN IN DT NN IN VBG CC VBG NN !', 'Hold fast to the principle of prioritizing convenience, aesthetic beauty and the outlook on the future in designing and building work!'],
  ['VB NN , NN CC JJ JJ NNS CC VB JJ NN NN !', 'Develop zero-energy, zero-carbon and green architectural technologies and introduce geothermal cooling-and-heating system!'],
  ['VB IN DT JJS NN DT NN IN VBG , VBG NN CC VBG NNS , DT NN NNS IN NN !', 'Ensure on the highest level the combination of designing, building work and building materials, the three elements of construction!'],
  ['VB IN NN DT NNS JJ TO NN PRP NN CC NN !', 'Sustain in construction the features unique to one\'s province and region!'],
  ['JJ IN NN DT NN IN NN NNS NNP CC JJ JJ NNS CC RB RB VB DT NN IN DT JJ NNP NN !', 'Complete with credit the construction of Mirae Scientists Street and other major projects and thus splendidly adorn the venue of the grand October celebration!'],
  ['NNP NN VBZ DT JJ VBG IN VBG NN IN VBG DT NN IN DT NN CC VBG DT VBG IN DT NNS .', 'Land administration is a patriotic undertaking of lasting significance for achieving the prosperity of the country and creating the well-being of the people.'],
  ['VB DT JJ NNP , DT JJ NN CC DT DT NNS VB IN IN DT NN TO NN NN , IN DT NN TO VB DT NNS IN DT NN !', 'Let the whole Party, the entire army and all the people turn out in the war to ameliorate nature, in the campaign to restore the forests of the country!'],
  ['RB NN DT NN IN VBG DT NNS IN NN IN JJ NN CC NN NN IN NN !', 'Vigorously conduct the movement of winning the titles of forest of socialist patriotism and model county in afforestation!'],
  ['VB PRP VB DT JJ NN IN NN CC JJ NNS CC NNS !', 'Let us cover the whole country with fruit and other trees and flowers!'],
  ['VB JJ , JJ CC JJ NNS IN DT NN IN NN NN !', 'Introduce scientific, industrial and intensive methods into the production of tree saplings!'],
  ['VB NN IN NN IN DT JJ NN RB IN TO VB DT NN IN DT NN !', 'Bring tideland under reclamation on a grand scale so as to widen the land of the country!'],
  ['VB DT DT NNS IN DT IN VB NNS TO DT NN , VBP JJ IN NNS CC VB NN TO DT NNS !', 'Turn all the rivers into those that give benefits to the country, are full of treasures and bring happiness to the people!'],
  ['NN IN JJ NNS TO VB NNS IN VBG , JJ NN , NN CC JJ NN !', 'Work out scrupulous measures to prevent damages from flooding, severe drought, storm and heavy snowfall!'],
  ['VB DT NN TO VB IN NNS IN JJ , JJ CC JJ NNS !', 'Hasten the work to build up roads for modern, heavy-duty and high-speed purposes!'],
  ['VB JJ NN TO NN NN IN DT NNS IN DT RB NN IN NN NNP !', 'Devote pure conscience to road maintenance like the members of the family workteam on Kubong Pass!'],
  ['VB DT NN NNS NN DT IN DT NNS CC NNS !', 'Let the cosmos flowers bloom all along the roads and railways!'],
  ['VB PRP VB DT JJ NN NN TO VB DT NN CC NN !', 'Let us launch a vigorous society-wide campaign to conserve the environment and nature!'],
  ['VB PRP VB CC VB NN IN JJ , NN CC NN NNS IN NN TO VB NN TO PRP$ JJ NN JJ IN NNS !', 'Let us protect and make use of underground, forest and marine resources in order to add glory to our legendary country full of treasures!'],
  ['VB PRP VB NNP JJR RB IN DT JJ CC JJ JJ NN , IN DT NN IN NN NN !', 'Let us develop Pyongyang more splendidly into a majestic and picturesque world-class city, as the centre of Songun culture!'],
  ['VB PRP VB DT JJ NN IN DT JJ NN IN VBG PRP IN NNP , NN IN DT NN !', 'Let us turn the whole country into a socialist fairyland by modelling it on Pyongyang, capital of the revolution!'],
  ['VB NNS , NNS , NNS CC NNS IN JJ CC JJ IN NN PRP JJ NN !', 'Keep streets, villages, mountains and rivers as neat and tidy as one\'s own courtyard!'],
  ['NNP DT JJ NN IN VBG CC VB NNS RB IN DT NN VBZ VBN JJ !', 'Plant a large number of flowering and cover plants so that no land is left bare!'],
  ['VBG JJ NN VBZ DT JJ NN IN VBG DT JJ NN .', 'Improving economic management is an urgent requirement for building an economic giant.'],
  ['VB PRP VB DT JJ NN NN IN PRP$ NN IN VBD IN DT VBG NN !', 'Let us establish an economic management method of our style as demanded by the developing reality!'],
  ['VB IN NNS RB NN PRP$ NN CC NN IN NNS IN NN IN JJ NN !', 'Ensure that producers fully discharge their responsibility and role as masters of production in economic management!'],
  ['VB JJ NN IN JJ NNS IN RB VBG TO JJ NNS !', 'Ensure maximum profit in economic activities while firmly adhering to socialist principles!'],
  ['NNP NN CC NN IN NN TO DT NN JJ NNS CC IN VBN IN JJ NN CC NN !', 'Conduct production and management in conformity to the objective economic laws and as required by modern science and technology!'],
  ['VB PRP VB DT NNP NN NN , VBN NN IN DT JJ NN !', 'Let us strengthen the Cabinet responsibility system, Cabinet-centred system in the economic work!'],
  ['NN IN DT JJ CC JJ NN IN NN NN CC NN NN VBN IN DT JJ NN IN JJ NN !', 'Work out a rational and effective strategy for business operation and enterprise management based on the national strategy for economic development!'],
  ['VB RB TO DT NNS IN JJ NN , NN CC VBG IN VBG NN !', 'Hold fast to the principles of scientific accuracy, viability and enlisting in planning work!'],
  ['RB VB DT NN IN NNS CC VB PRP$ JJ NN !', 'Radically improve the quality of products and enhance their competitive edge!'],
  ['NN VBZ DT RB NN TO VB !', 'Self-reliance is the only way to survive!'],
  ['VB NN IN DT JJ VBG CC VBN IN DT NN IN NN , VBG RB DT NN IN NN !', 'Put production on a normal footing and speed up the advance of socialism, holding aloft the banner of self-reliance!'],
  ['VB PRP VB NN , VBG IN PRP$ JJ NN CC NN !', 'Let us realize modernization, relying on our own strength and technology!'],
  ['VB JJ IN DT NN TO NNS CC VB JJ NN IN JJ CC JJ NNS CC NN !', 'Get rid of the proclivity to imports and ensure domestic production of raw and other materials and equipment!'],
  ['VB JJ NN IN JJ NN , JJ NN CC JJ NN IN DT NNS !', 'Establish exacting order of regular operation, regular repair and regular maintenance at all units!'],
  ['VB IN NN IN PRP$ NNS CC NNS , NN IN NN NNS , CC VB JJ NN IN PRP IN DT NN IN VBG NNS !', 'Be in charge of your workplaces and villages, split into square metres, and take good care of them with the attitude as befitting masters!'],
  ['NNP VBZ VBN NN CC NN .', 'Economy means increased production and patriotism.'],
  ['VB IN DT NN IN NN , DT NN IN NN NN CC NN , CC DT NN IN NN CC NN TO DT JJ !', 'Economize on every watt of electricity, every drop of fuel oil and water, and every gramme of coal and cement to the maximum!'],
  ['PRP VBZ DT NN MD IN PRP$ NNP TO VB IN DT JJS VBN DT JJS NN IN NN , WDT MD VB VBD IN DT NN .', 'It is a firm will of our Party to create at the fastest speed the highest level of civilization, which would be envied by the world.'],
  ['VB PRP VB IN DT NN IN NN IN DT JJ NN TO VB PRP IN DT NN IN NN , DT JJ NN !', 'Let us bring about a revolution in education in the new century to develop ours into a country of education, a talented nation!'],
  ['RB VB DT NN IN DT JJ CD NN JJ NN !', 'Decisively improve the quality of the universal 12-year compulsory education!'],
  ['VB DT NNS IN NN IN JJ , JJ CC JJ NNS !', 'Develop the contents of education into practicable, comprehensive and modern ones!'],
  ['RB VB JJ NN IN JJ NN IN NNS TO VB JJ NN !', 'Closely combine theoretical education with practical education for students to learn useful knowledge!'],
  ['VB PRP RB VB RB JJ NN , VBG PRP IN NN IN DT JJ JJ NNS VBG DT JJ NNP , DT JJ NN CC DT DT NNS !', 'Let us vigorously push forward educational work, viewing it as one of the important national affairs involving the entire Party, the whole country and all the people!'],
  ['VB PRP RB VB RB NN IN JJ CC NN NN CC VB IN DT VBG NNS TO VB JJ CC NN !', 'Let us closely combine family education with social and school education and bring up the coming generations to be honest and sound!'],
  ['VB NNS VB NNS CC NNS IN DT NN IN DT NN !', 'Let teachers become roots and foundations for the future of the motherland!'],
  ['VB PRP VB DT DT NNS RB VBN IN NN CC NN , CC VB PRP$ NN IN DT JJ CC JJ NN , DT JJ NN !', 'Let us make all the people well versed in science and technology, and develop our country into a scientific and technological power, a talented nation!'],
  ['VBN IN VBG DT VBG NN RB VBN IN NN CC NN IN DT NNS IN VBG NN NN IN NNS !', 'Speed up making the working class well versed in science and technology with the rooms for disseminating sci-tech knowledge as bases!'],
  ['NNP NN CC NNS VBP JJ IN VBG DT JJ NN CC VBG DT DT NNS IN NN CC JJ NN .', 'Physical culture and sports are important in demonstrating the national strength and preparing all the people for labour and national defence.'],
  ['VB PRP VB DT NN IN PRP$ NN TO IN IN DT NNS NN IN DT JJS NN JJ !', 'Let us raise the status of our country to that of a sports power at an earliest date possible!'],
  ['VB PRP RB VB DT NNS NN IN DT NN !', 'Let us fiercely raise the sports wind across the country!'],
  ['DT NN IN DT VBG NN VBZ DT NN IN DT NN !', 'The height of a medal-awarding podium represents the prestige of the motherland!'],
  ['VB DT NN IN NN NNP IN DT NNS IN DT NN IN VBG JJR NN NNS !', 'Glorify the honour of Songun Korea before the eyes of the world by winning more gold medals!'],
  ['NNP NNS NNS IN DT JJ NN , DT NN DT JJ NNS VBD !', 'Play sports games in an offensive way, the way the anti-Japanese guerrillas did!'],
  ['VB PRP VB NNS VBN CC NN IN PRP$ JJ NN !', 'Let us make sports mass-based and part of our everyday life!'],
  ['VB NN NNS CC NNS NNS VBD IN DT NNS CC VB JJ VBG IN JJ NN !', 'Encourage folk games and sports events participated by the masses and develop physical training for national defence!'],
  ['NNS CC JJ NNS NNS , CC NNS CC NN !', 'Journalists and other media persons, and creators and artistes!'],
  ['VB IN DT JJ NN IN NN NNS !', 'Bring about a fresh revolution in mass media!'],
  ['VB NN NNS VB DT VBG NN JJ TO DT NNS CC DT NN IN DT NNS !', 'Let mass media become a travelling companion dear to the masses and a pathfinder of the times!'],
  ['VB JJR NNS IN JJ NNS JJ IN RB JJ DT NN CC VBG NN NN IN NN IN PRP$ NN NNS CC NNS !', 'Make larger numbers of ideological "missilescapable of severely damaging the enemy and instilling firm confidence in victory among our service personnel and people!'],
  ['VB PRP NN DT VBN NN IN DT NNP IN VBG JJ NNS IN NNS !', 'Let us support the Songun-based leadership of the Party by creating large numbers of masterpieces!'],
  ['VB IN DT JJ CC JJ NN IN VBG NNS VBN IN DT NN NNP TO VB IN NNS IN JJ NNS !', 'Learn from the revolutionary and militant manner of creating works developed by the Moranbong Band to bring about innovations in creative activities!'],
  ['VB JJ NNS IN NN CC NN IN VB DT JJ NNS CC JJ NNS IN DT RB JJ NNS IN NNP . NN !', 'Create excellent works of art and literature that portray the revolutionary careers and immortal exploits of the peerlessly great men of Mt. Paektu!'],
  ['VB DT NNS IN DT JJ NN IN NN , VBG IN DT NN IN NNS !', 'Kindle the flames of a fresh revolution in cinema, starting from the production of animations!'],
  ['VB DT VBG NNS NN IN IN NN CC NN IN VBG JJ NNS IN NNS IN NN DT NNP PRP NNS CC VBG NN NNS !', 'Make the advancing ranks brim over with enthusiasm and optimism by producing large numbers of songs that champion the Party\'s policies and enlivening folk songs!'],
  ['VB PRP VB DT JJ NN IN DT NN IN DT NNS CC VB DT NNS VBN !', 'Let us turn the whole country into a land of the arts and make the arts mass-based!'],
  ['VB DT NN NN IN JJ CC VBG NN IN RB VBG VBN JJ CC JJ NNS !', 'Make every workplace overflow with revolutionary and fighting morale by actively conducting mass-based cultural and artistic activities!'],
  ['NN VBZ DT NN CC NN IN DT JJ JJ NN NN .', 'Devotion is the attribute and lifeblood of the socialist public health service.'],
  ['NNP NNS JJ NN DT NN DT JJ NNS IN DT NN NN VBD !', 'Show people utmost devotion the way the medical workers in the Chollima era did!'],
  ['VB DT NN CC NN NN CC JJ CC JJ JJ NN RB IN TO VB JJS VB TO DT NNS IN DT JJ JJ NN NN !', 'Improve the hygiene and anti-epidemic work and preventive and curative medical care so as to give fullest play to the advantages of the socialist public health system!'],
  ['VB TO NN NN CC DT JJ NN NN !', 'Bring to perfection telemedicine and the medical information network!'],
  ['VB DT NN IN NNS NNS JJ TO VBG DT NNS PRP NN !', 'Boost the production of highly-efficacious medicines conducive to promoting the people\'s health!'],
  ['VB PRP VB DT JJ NN NN IN JJ NNS CC JJ CC JJ NN !', 'Let us make the whole society pulsate with national sentiments and noble and beautiful lifestyle!'],
  ['VB PRP VB JJ NNS IN NN CC NN IN DT JJ NN !', 'Let us establish cultured ways in production and life on a high level!'],
  ['VB PRP VB DT JJ JJ NN IN PRP$ NN CC VB CC VB PRP !', 'Let us conserve the excellent cultural heritage of our nation and inherit and develop them!'],
  ['DT NNS PRP NN VBZ DT JJ JJ NN IN VBG DT VBG NN CC VBZ JJ IN DT NNS PRP NNS .', 'The people\'s government is a powerful political weapon in building a thriving nation and is responsible for the people\'s livelihoods.'],
  ['VB PRP JJ VB DT RBS JJ VBN JJ NN IN PRP$ JJ NN !', 'Let us further develop the most advantageous people-centred socialist system of our own style!'],
  ['VB PRP VB PRP$ NNS PRP NN TO VB PRP NN !', 'Let us consolidate our people\'s power to make it rock-solid!'],
  ['VB PRP VB JJ VB TO DT NNS CC MD IN NN RB IN TO VB NN IN JJ IN DT NNS IN NN IN NN VBZ IN NN !', 'Let us give full play to the advantages and might of socialism so as to make socialism as different in all respects from capitalism as heaven is from earth!'],
  ['VB DT JJ NNS CC NNS IN DT NNP CC DT NN VB DT NNS IN PRP VBP !', 'Let the people-oriented policies and favours of the Party and the state reach the people as they are!'],
  ['RB VB DT NNS PRP VBG NNS RB IN TO VB DT VBG IN DT NNPS NNP CC NN NN !', 'Steadily improve the people\'s living standards so as to make the cheering for the Workers\' Party and socialism resound!'],
  ['VB PRP VB DT JJ NNS IN VBG NN IN VBN NNS , DT RB IN DT NN TO NN PRP CC NNS IN NNS DT NN IN DT NN IN VBZ VB NN JJ RB !', 'Let us make the laudable traits of taking care of orphaned children, the elderly with no one to support them and people with disabilities a tradition of the country that has become one large family!'],
  ['VB PRP VB DT JJ JJ NN IN NN NN IN NN IN VBG NN TO DT JJ NN !', 'Let us create a thoroughgoing revolutionary atmosphere of law observance throughout society by strengthening obedience to the socialist law!'],
  ['VB PRP DT NN DT NN PRP NN CC NN RB IN DT JJ NN IN JJ NN !', 'Let us all observe the country\'s law and order voluntarily with a noble sense of civic duty!'],
  ['VB JJ CC JJ NNS NN PRP$ JJ NN CC NN IN VBG DT NN , DT NNS , DT NN CC DT NNS !', 'Let judicial and prosecutorial organs fulfil their sacred mission and duty of defending the leader, the policies, the system and the people!'],
  ['VB NN IN NN NN CC JJ NN TO RB NN DT VBG IN DT VBG NN IN NN !', 'Intensify education in law observance and law-based struggle to reliably guarantee the building of a thriving nation by law!'],
  ['VB DT NNS IN DT NN NNS VB JJ NNS IN DT JJ CC JJ NNS CC JJ CC JJ NNS IN DT NNS !', 'Let the officials in the law-enforcement organs become fierce tigers for the unsound and hostile elements and faithful and true servants for the people!'],
  ['VB IN DT VBN NN IN DT JJ NNS IN VBG NN RB IN VBN IN DT NNP PRP NNS !', 'Build up the single-hearted unity of the revolutionary ranks by enforcing law properly as required by the Party\'s policies!'],
  ['NN DT NN NN RB IN VBG IN DT NNS !', 'Wage the class struggle dynamically by relying on the masses!'],
  ['VB JJ NN CC NN CC VB DT NNP , NN CC JJ NNS RB !', 'Establish revolutionary discipline and order and keep the Party, state and military secrets strictly!'],
  ['WRB JJ NNS VBP JJ , DT JJ NN VBZ JJ CC DT JJ NN VBZ VBN IN IN DT NNS IN VBG DT VBG JJ NN .', 'When young people are astir, the whole country becomes astir and a revolutionary upsurge is brought about on all fronts of building a thriving socialist country.'],
  ['VB PRP VB JJ NNS IN DT JJ NN TO VB DT JJ NNP NNP FW PRP NN !', 'Let us become young heroes in the worthwhile struggle to glorify the great Kim Jong Un\'s era!'],
  ['NNP NNS , VB NN NNS WP VBP RB JJ TO DT NNP PRP JJ NN IN NN !', 'Young people, be vanguard fighters who are unfailingly faithful to the Party\'s revolutionary cause of Songun!'],
  ['RB NN JJ RB , VBG DT NNP !', 'Always advance straight ahead, following the Party!'],
  ['VB JJS NN TO DT JJ NN CC NN IN NN JJ NN CC VBG IN DT NNP IN DT NN TO VB IN DT JJ NN IN NN !', 'Give fullest scope to the heroic spirit and mettle as befit reliable point-men and wing of the Party in the struggle to carry out the revolutionary cause of Songun!'],
  ['NNP DT NN IN DT NN NN IN DT NN NN VBG RB DT NN NNP VBN IN DT NNP !', 'Towards the trench on the first line of the Songun revolution singing loudly the song Train Bound for the Front!'],
  ['VB NN PRP NN NNP NNS CC NNP NN NNS , WP VBP JJ TO VBD RB PRP$ NN CC NNS IN DT NN IN PRP$ RB NN !', 'Become today\'s Ri Su Boks and Jo Kun Sils, who are ready to lay down their youth and lives for the sake of their only motherland!'],
  ['VB IN NN CC NN IN NN TO DT NNP PRP VB !', 'Go through fire and water in response to the Party\'s call!'],
  ['VB NN TO PRP$ NN IN PRP$ NNS CC NNS VBD !', 'Add brilliance to your youth like your fathers and mothers did!'],
  ['VB IN DT NN NN IN RB NN NNS JJ IN DT NN IN NN , NN CC VBG NN !', 'Build up the youth league into steely combat ranks strong in the sense of organization, unity and fighting efficiency!'],
  ['NNP DT VBG NN IN DT VBG NNS PRP NNS CC VB JJS VB TO DT JJ NN IN PRP$ NNS !', 'Enhance the fighting efficiency of the working people\'s organizations and give fullest play to the patriotic zeal of their members!'],
  ['NN JJ VBN NNS CC VB DT NNS IN JJ NN NN NN DT JJ NN !', 'Launch brisk mass-based movements and make the flames of socialist emulation drive sweep the whole country!'],
  ['DT JJ RB NN IN DT JJ NN IN DT NN NN NNS JJ CC JJ VBG NN CC VBG NN IN WDT TO VB DT NN RB IN VBG IN IN DT NN .', 'The general onward march of the new century of the Juche era demands revolutionary and militant fighting spirit and working style with which to make a leap forward while looking out over the world.'],
  ['VB PRP VB DT JJ NN IN DT NNS , DT VBN IN NNP , IN VBZ IN PRP$ NNP PRP JJ NN , VBG NN CC JJ NN !', 'Let us create a new spirit of the times, the speed of Korea, by means of our Party\'s revolutionary mode, fighting style and creative way!'],
  ['NNP VBZ WP PRP VBZ VBN TO VBP !', 'Korea does what it is determined to do!'],
  ['DT IN RB !', 'All at once!'],
  ['NNP IN DT NNS VBN IN DT NNP IN DT NN PRP VBZ VBN CC IN DT NN PRP VBZ !', 'Carry out the tasks given by the Party within the time it has set and on the level it requires!'],
  ['VB PRP VB IN DT VBG NN , DT NN IN VBG IN DT NNP PRP NNS CC NNS TO DT NN , CC DT JJ VBG NN IN DT JJ NNS PRP NNP NN CD !', 'Let us learn from the fighting spirit, the spirit of carrying out the Party\'s lines and policies to the death, and the meticulous working style of the Korean People\'s Army Unit 267!'],
  ['VB DT NNS VBD IN DT JJ NNS VB JJ CC JJ NNS IN VBG DT NNP PRP NNS !', 'Let the units visited by the great leaders be exemplary and standard ones in implementing the Party\'s policies!'],
  ['VB NNP VB DT NN IN DT NNS IN VBG NN PRP NNP NN , NNP VBN !', 'Let Pyongyang lead the country in all aspects by creating today\'s Pyongyang spirit, Pyongyang speed!'],
  ['VB PRP VB NN NNS IN DT NNS CC NN JJ NNS !', 'Let us create prototype units in all sectors and effect joint innovations!'],
  ['VB JJ IN NNS CC NNS CC VB JJ NNS RB !', 'Get rid of stereotypes and formulae and create new things constantly!'],
  ['NNP NNS IN NNS IN DT NN WRB NNS VBP VBG JJ CC NN JJ NN !', 'Cover hundreds of kilometres at a stretch when others are taking tenth or one hundredth step!'],
  ['VB PRP$ NNS RB VBN IN DT NN CC VB IN IN DT NN !', 'Keep your feet firmly planted on this land and look out over the world!'],
  ['VB PRP VB JJ CC VB NN TO PRP$ JJ NNS !', 'Let us hold dear and add brilliance to our own things!'],
  ['NNP IN DT NNP PRP NNS IN RB IN DT NNS IN DT NN VBG NNP NN VBD !', 'Carry out the Party\'s policies as exactly in all aspects as the Chonji Lubricating Oil Factory did!'],
  ['DT JJR NNS PRP VB , DT RBR DT NN VBZ ; DT JJR NNS PRP VB , DT RB DT NN VBZ .', 'The more books we read, the earlier the country prospers; the less books we read, the later the country prospers.'],
  ['VB PRP VB DT NN PRP NN IN VBG IN NN !', 'Let us establish the guerrilla\'s way of studying throughout society!'],
  ['VB RB DT NN IN VBG IN NN NN IN PRP VBZ VBN IN , IN DT NN IN DT NN CC IN VBG DT NN NN !', 'Overcome thoroughly the manner of working like extinguishing fire after it has broken out, like a flash in the pan and like conducting a shock campaign!'],
  ['IN JJ IN PRP VBP IN DT VBN NN NNP NNP FW , NN CC NN IN RB IN NN VBP DT NN IN PRP !', 'As long as we are with the respected Comrade Kim Jong Un, sorrow and hardship as well as joy are an honour for us!'],
  ['VB PRP VB RB RB IN NN CC IN NN !', 'Let us live not merely for today but for tomorrow!'],
  ['VB DT JJ NN IN DT NN CC DT NN IN NN NN IN PRP$ JJ NN VBZ NN NNS IN NN IN PRP$ NN !', 'Acquire a noble outlook on the revolution and the future that one year of our hard work means ten years of advance for our motherland!'],
  ['VB PRP VB DT JJ NN NN JJR IN DT NN PRP VBP DT JJS IN DT NNP .', 'Let us make the whole country resound louder with the song We Are the Happiest in the World.'],
  ['NNP IN DT JJ NN , VBN IN NN IN JJ NN CC NN !', 'Forward towards a bright future, filled with confidence in sure victory and optimism!'],
  ['DT NN IN DT NNP PRP NNS VBZ IN DT NNS NNS .', 'The destiny of the Party\'s policies rests on the officials\' shoulders.'],
  ['VB NN CC NN NNS IN NN PRP JJ JJ !', 'Be standard-bearers and vanguard fighters in today\'s general offensive!'],
  ['VB JJ NNS IN DT NNP PRP NNS CC JJ NNS WP VB PRP IN DT JJ NN !', 'Be ardent supporters of the Party\'s policies and thoroughgoing fighters who implement them in a do-or-die spirit!'],
  ['VB PRP VB CC NN IN DT NNS IN DT CD PRP , DT NN IN VBG DT NNP PRP NN IN VBG RB DT NN IN NN !', 'Let us live and work like the officials in the 1970s, the period of laying the Party\'s foundation for carrying forward the cause of Juche!'],
  ['VB CC NN NNS RB IN DT VBG NNS IN DT JJ NN IN DT NN !', 'Organize and guide undertakings dynamically like the commanding officers of the revolutionary army on the frontline!'],
  ['VB JJ NN CC JJ NN !', 'Intensify on-site guidance and political work!'],
  ['VBG , NN CC NN , DT IN DT JJ NN CC IN VBG VBN !', 'Planning, command and review, all in a three-dimensional way and at lightning speed!'],
  ['VB JJ NNS IN DT JJ NN TO VB DT NNS IN DT NNS PRP VBG IN DT NN !', 'Make tireless efforts with an extraordinary determination to resolve the problems of the people\'s living at any cost!'],
  ['VBP VBG IN DT JJ CC JJ NN !', 'Do everything in an innovative and scientific way!'],
  ['NNP DT NNS IN NNS NN IN VBG DT NN IN PRP$ NNS !', 'Read the minds of producers first before measuring the quantity of their products!'],
  ['RB NN NN VBZ RB DT NN TO VB NN !', 'Supply service work is immediately the struggle to defend socialism!'],
  ['NN RB NN , NN , NN CC NN !', 'Sweep away defeatism, self-preservation, expediency and self-centeredness!'],
  ['PRP VBZ DT JJ NN IN DT DT NN NNS CC JJ NN IN DT NN TO VB DT NN TO DT NN IN JJ NN IN VBZ VBD CD NNS .', 'It is a long-cherished desire of all the fellow countrymen and urgent task of the nation to put an end to the tragedy of national division that has lasted 70 years.'],
  ['VB PRP VB DT VBN CC JJ VBN NN IN DT NN IN VB JJ TO DT NN VBZ IN DT JJ NNPS NNP FW NN NNP NNP FW .', 'Let us build a dignified and prosperous reunified country on this land without fail true to the lifetime wishes of the great Comrades Kim Il Sungand Kim Jong Il.'],
  ['VB PRP VB JJ DT NN NNS IN JJ NN CC DT JJ NNS IN NNS CC JJ NNS IN JJ NN JJ TO DT NN !', 'Let us hold high the three charters for national reunification and the north-south declarations as charters and great programmes for national reunification common to the nation!'],
  ['VB DT JJ NN VB NNS TO JJ IN DT JJ NN TO JJ NN IN DT NN WDT NNS DT CD DT NN IN JJ NN !', 'Let the whole nation join efforts to open up a broad avenue to independent reunification in this year which marks the 70th anniversary of national liberation!'],
  ['VB PRP VB DT NN TO NN IN IN NNS CC VB JJ NN RB IN DT VBN NN IN IN PRP$ NN PRP !', 'Let us put an end to interference by outside forces and achieve national reunification independently under the unfurled banner of By Our Nation Itself!'],
  ['VB PRP VB IN DT JJ VB IN DT NN NNS IN DT NN IN NNS DT CD DT NN IN DT NNP CD NNP NNP !', 'Let us bring about a great turn in the inter-Korean relations in this year that marks the 15th anniversary of the June 15 Joint Declaration!'],
  ['VB DT JJ NN VB IN CC VB DT JJ NN IN DT NN IN NN NNS IN JJ NN TO DT RB JJ NN PRP JJ VB !', 'Let the whole nation turn out and write a new chapter in the history of inter-Korean relations in hearty response to the peerlessly great man\'s patriotic call!'],
  ['VB PRP RB VB DT JJ NNS CC NNS IN NN NNS IN DT PRP CC RB JJ NNS !', 'Let us determinedly thwart the military provocations and schemes of war games by the US and south Korean warmongers!'],
  ['VB PRP NN IN IN DT JJ NN TO NN DT PRP NN JJ NNS , DT NN NN IN JJ NN CC NN , IN IN RB NNP !', 'Let us rise up in the nationwide struggle to drive the US imperialist aggressive forces, the root cause of national misfortune and war, out of south Korea!'],
  ['VB PRP RB VB DT NN JJ NNS NNS IN DT PRP CC PRP$ NN NNS !', 'Let us resolutely frustrate the anti-DPRK "human rightsschemes by the US and its vassal forces!'],
  ['VB PRP VB RB TO DT NNS IN PRP$ JJ NN , NN CC NN !', 'Let us hold fast to the principles of our foreign policy-independence, peace and friendship!'],
  ['VB PRP VB DT JJ NNS CC JJ VB IN DT NN IN JJ NNS !', 'Let us maintain the revolutionary principles and independent stand with all consistency in foreign relations!'],
  ['VB PRP VB JJ NNS IN DT JJ CC NN NN , VBG JJ NN TO DT NN CC NNS IN DT NN !', 'Let us develop foreign relations in a multilateral and proactive way, giving top priority to the dignity and interests of the country!'],
  ['VB PRP VB RB CC JJ NNS IN DT NNS IN NN DT NN IN PRP$ NN CC VBP RB TO PRP !', 'Let us develop friendly and cooperative relations with all countries that respect the sovereignty of our nation and are friendly to us!'],
  ['DT NNP NNS , NNS CC NNS IN DT NNS PRP NNP CC NNS !', 'All Party members, officers and men of the People\'s Army and people!'],
  ['DT VBG NN IN DT JJ JJ IN DT CD DT NNS IN JJ NN CC NNP VBG VBZ VBN VBN .', 'An opening salvo of the general offensive for the 70th anniversaries of national liberation and Party founding has been fired.'],
  ['DT JJ NN IN NN , DT NN IN DT NNS IN NN CC DT JJ JJ NNS VB TO VB DT JJ NN RB IN NN MD VB , VB IN JJ DT NN IN JJ NN CC VBG NN IN PRP$ NN NNS CC NNS , WP VBP VBG RB IN DT NN IN NN IN DT NNS , CC VB NN CC NN IN DT VBG NNS .', 'The revolutionary spirit of Paektu, the spirit of the blizzards of Paektu and the anti-Japanese revolutionary forerunners\' call to keep the revolutionary faith even if one may die, stir up further the confidence in sure victory and fighting spirit of our service personnel and people, who are charging forward along the road of Juche against all odds, and inspire loyalty and passion in the advancing ranks.'],
  ['DT NN MD NN DT VBG NN IN DT NN NNS CC NNS , WP VBP VBG IN JJ NN NN , JJ , VBG DT NN IN DT VBN NN NNP NNP FW , DT JJ NN IN NN .', 'No force can check this sweeping advance of the service personnel and people, who are marching in fine array arm-in-arm, shoulder-to-shoulder, following the leadership of the respected Comrade Kim Jong Un, a great man of Paektu.'],
  ['DT NNS VBG DT VBG NNS IN DT JJ NNPS NNP FW NNP CC NNP NNP FW MD RB RB IN DT NNP IN PRP$ JJ NNS IN VB RB NN CC NN , CC RB VB PRP TO JJ NNS .', 'The flags bearing the beaming images of the great Comrades Kim Il Sung and Kim Jong Il will fly forever in the van of our revolutionary ranks that achieve only victory and glory, and always inspire us to fresh victories.'],
  ['DT RB IN DT NN IN NN NN !', 'All forward towards the venue of victory celebration!'],
  ['NNP VB DT JJ NN IN DT JJ NN CC DT CD DT NN IN JJ NN !', 'Long live the great victory in the anti-Japanese war and the 70th anniversary of national liberation!'],
  ['NNP VB DT CD DT NN IN DT NNPS NNP IN NNP !', 'Long live the 70th anniversary of the Workers\' Party of Korea!']
];
